/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cosechaoperacionesv1;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * POLITECNICO GRACOLOMBIANO
 * Pradigmas de Programacion 
 * Ingenieria Software
 * @author acastroc
 * Albeiro Castro
 * Codigo:2011023897
 * Fecha de Inicio:12-06-20
 */
//Interfaz de inicio de juego movimiento y toda ejecucion del juego
public class Mover extends javax.swing.JFrame {
 private int x, y;
 private int movimientoX; 
 private int movimientoy;
 private int distanmaxX;

    public Mover() {
        initComponents();
        Panel.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        CanastoLab = new javax.swing.JLabel();
        Titulo2Lab = new javax.swing.JLabel();
        FondoLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PanelKeyPressed(evt);
            }
        });
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CanastoLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesJuegoParadigmas/interfaz-juego-canasto/canasto2.png"))); // NOI18N
        Panel.add(CanastoLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        Titulo2Lab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesJuegoParadigmas/interfaz-juego-canasto/titulo.png"))); // NOI18N
        Panel.add(Titulo2Lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        FondoLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesJuegoParadigmas/interfaz-juego-sumar/fondo2-12-0620.png"))); // NOI18N
        FondoLab.setText("jLabel1");
        Panel.add(FondoLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1080, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PanelKeyPressed
      x=CanastoLab.getX();
      y=CanastoLab.getY();
        System.out.println(CanastoLab.getLocation());
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_UP: if(CanastoLab.getY()>=390) CanastoLab.setLocation(x, y -2);break; //Codigo para movimiento asi arriba
            case KeyEvent.VK_DOWN: if(CanastoLab.getY()<=455)CanastoLab.setLocation(x, y+2);break; //Codigo para movimiento asi abajo
            case KeyEvent.VK_RIGHT: if(CanastoLab.getX()<=838)CanastoLab.setLocation(x+2, y);break; //Codigo para movimineto asi la derecha
            case KeyEvent.VK_LEFT:if(CanastoLab.getX()>=-6) CanastoLab.setLocation(x-2, y);break;// Codigo para movimiento asi izquierda
        }
    }//GEN-LAST:event_PanelKeyPressed
//Realizado por @author acastroc 12-06-20
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CanastoLab;
    private javax.swing.JLabel FondoLab;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Titulo2Lab;
    // End of variables declaration//GEN-END:variables
}
